//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeButtonDemo.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostLike
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public string UserAgent { get; set; }
        public string IPAddress { get; set; }
        public bool UserLike { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
